name: acquire-activation-file

# If you change the major version of Unity and cannot build with GitHub Actions, please follow these steps to resolve the issue.
# 1. Enter the version of Unity you are trying to use in the UNITY_MAJOR_VERSION field of your GitHub secrets settings. ex) 2021.3.0f1 / 2022.1.0f1
# 2. Manually start the acquire-activation-file workflow. download an artifact file such as unity_vyyyy.M.mfp.alf.
# 3. Go to https://license.unity3d.com/manual and upload the alf file you just downloaded.  Follow the instructions and you will get the ulf file.  Copy the contents and paste it into UNITY_LICENSE in secrets, then run the build job again.

on:
  workflow_dispatch: { }
  workflow_call:
    secrets:
      CLIENT_SECRET:
        required: true

jobs:
  activation:
    name: request-manual-activation-file
    runs-on: ubuntu-latest
    steps:
      - name: request-manual-activation-file
        id: getManualLicenseFile
        uses: game-ci/unity-request-activation-file@v2
        with:
          unityVersion: ${{ vars.UNITY_MAJOR_VERSION }}
      - name: expose-as-artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.getManualLicenseFile.outputs.filePath }}
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}
