name: standalone-deploy

on:
  workflow_call:
    inputs:
      PROJECT_NAME:
        required: true
        type: string

env:
  PROJECT_PATH: .
  PROJECT_NAME: ${{ inputs.PROJECT_NAME }}

jobs:
  build-windows:
    name: build-for-${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
    outputs:
      buildVersion: ${{ steps.build.outputs.buildVersion }}
    steps:
      - name: checkout-self
        uses: actions/checkout@v4
        with:
          repository: paochanz/UnityUtilities
          fetch-depth: 0
      - name: prune-previous-images
        run: docker image prune --all --force
        shell: bash
      - name: cache
        uses: ./.github/actions/cache-files
        env:
          target_platform: ${{ matrix.targetPlatform }}
      - name: build
        uses: ./.github/actions/unity-build
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ vars.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          target_platform: ${{ matrix.targetPlatform }}
          unity_custom_image: ${{ vars.UNITY_CUSTOM_IMAGE_WINDOWS }}
      - name: chown
        shell: bash
        run: sudo chown -R $USER:$USER $GITHUB_WORKSPACE
      - name: checkout-self
        uses: actions/checkout@v4
        with:
          repository: paochanz/UnityUtilities
          fetch-depth: 0

  build-mac:
    name: build-for-${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX # Build a macOS standalone.
    steps:
      - name: checkout-self
        uses: actions/checkout@v4
        with:
          repository: paochanz/UnityUtilities
          fetch-depth: 0
      - name: prune-previous-images
        run: docker image prune --all --force
        shell: bash
      - name: cache
        uses: ./.github/actions/cache-files
        env:
          target_platform: ${{ matrix.targetPlatform }}
      - name: build
        uses: ./.github/actions/unity-build
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ vars.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          target_platform: ${{ matrix.targetPlatform }}
          unity_custom_image: ${{ vars.UNITY_CUSTOM_IMAGE_MAC }}
      - name: chown
        shell: bash
        run: sudo chown -R $USER:$USER $GITHUB_WORKSPACE
      - name: checkout-self
        uses: actions/checkout@v4
        with:
          repository: paochanz/UnityUtilities
          fetch-depth: 0

  post-build-mac:
    name: notarize-for-${{ matrix.targetPlatform }}
    runs-on: macos-latest
    needs:
      - build-mac
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX
    steps:
      - name: checkout-self
        uses: actions/checkout@v4
        with:
          repository: paochanz/UnityUtilities
          fetch-depth: 0
      - name: notarize
        uses: ./.github/actions/notarize-mac-app
        env:
          APPLE_CERTIFICATES_P12: ${{ secrets.APPLE_CERTIFICATES_P12 }}
          APPLE_CERTIFICATES_PASSWORD: ${{ secrets.APPLE_CERTIFICATES_PASSWORD }}
          APPLE_ENTITLEMENT: ${{ vars.APPLE_ENTITLEMENT }}
          APPLE_CONNECT_IDENTITY: ${{ vars.APPLE_CONNECT_IDENTITY }}
          APPLE_CONNECT_ID: ${{ vars.APPLE_CONNECT_ID }}
          APPLE_CONNECT_PASSWORD: ${{ secrets.APPLE_CONNECT_PASSWORD }}
          APPLE_CONNECT_TEAM: ${{ vars.APPLE_CONNECT_TEAM }}
          target_platform: ${{ matrix.targetPlatform }}
          build_path: ${{ env.PROJECT_PATH }}/build/${{ matrix.targetPlatform }}/${{ env.PROJECT_NAME }}
      - name: checkout-self
        uses: actions/checkout@v4
        with:
          repository: paochanz/UnityUtilities
          fetch-depth: 0

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs:
      - build-windows
      - post-build-mac
    steps:
      - name: checkout-self
        uses: actions/checkout@v4
        with:
          repository: paochanz/UnityUtilities
          fetch-depth: 0
      - name: steam
        uses: ./.github/actions/deploy-to-steam
        env:
          STEAM_USERNAME: ${{ vars.STEAM_USERNAME }}
          STEAM_CONFIG_VDF: ${{ secrets.STEAM_CONFIG_VDF }}
          STEAM_APP_ID: ${{ vars.STEAM_APP_ID }}
          STEAM_APP_ID_DEMO: ${{ vars.STEAM_APP_ID_DEMO }}
          DEMO_IN_PARENT: ${{ vars.DEMO_IN_PARENT }}
          build_version: ${{ needs.build-windows.outputs.buildVersion }}
      - name: chown
        shell: bash
        run: sudo chown -R $USER:$USER $GITHUB_WORKSPACE
      - name: checkout-self
        uses: actions/checkout@v4
        with:
          repository: paochanz/UnityUtilities
          fetch-depth: 0
      - name: release-on-github
        uses: ./.github/actions/create-release
        env:
          deploy_platform: both
      - name: chown
        shell: bash
        run: sudo chown -R $USER:$USER $GITHUB_WORKSPACE
      - name: checkout-self
        uses: actions/checkout@v4
        with:
          repository: paochanz/UnityUtilities
          fetch-depth: 0
