name: standalone-deploy

on:
  workflow_call:
    inputs:
      PROJECT_NAME:
        required: true
        type: string
      STEAM_APP_ID:
        required: true
        type: string
      STEAM_APP_ID_DEMO:
        required: false
        type: string
      UNITY_CUSTOM_IMAGE_WINDOWS:
        required: false
        type: string
      UNITY_CUSTOM_IMAGE_MAC:
        required: false
        type: string

env:
  PROJECT_PATH: .
  STEAM_APP_ID: ${{ inputs.STEAM_APP_ID }}
  STEAM_APP_ID_DEMO: ${{ inputs.STEAM_APP_ID_DEMO }}
  UNITY_CUSTOM_IMAGE_WINDOWS: ${{ inputs.UNITY_CUSTOM_IMAGE_WINDOWS }}
  UNITY_CUSTOM_IMAGE_MAC: ${{ inputs.UNITY_CUSTOM_IMAGE_MAC }}

jobs:
  build-windows:
    name: build-for-${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
    outputs:
      buildVersion: ${{ steps.build.outputs.buildVersion }}
    steps:
      - name: checkout-self
        uses: actions/checkout@v4
        with:
          repository: shirokurohitsuji/UnityUtilities
          fetch-depth: 0
      - name: prune-previous-images
        run: docker image prune --all --force
        shell: bash
      - name: cache
        uses: ./.github/actions/cache-files
        env:
          target_platform: ${{ matrix.targetPlatform }}
      - name: build
        uses: ./.github/actions/unity-build
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ vars.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          target_platform: ${{ matrix.targetPlatform }}
          unity_custom_image: ${{ env.UNITY_CUSTOM_IMAGE_WINDOWS }}
      - name: checkout-self
        uses: actions/checkout@v4
        with:
          repository: shirokurohitsuji/UnityUtilities
          fetch-depth: 0

  build-mac:
    name: build-for-${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX # Build a macOS standalone.
    steps:
      - name: checkout-self
        uses: actions/checkout@v4
        with:
          repository: shirokurohitsuji/UnityUtilities
          fetch-depth: 0
      - name: prune-previous-images
        run: docker image prune --all --force
        shell: bash
      - name: cache
        uses: ./.github/actions/cache-files
        env:
          target_platform: ${{ matrix.targetPlatform }}
      - name: build
        uses: ./.github/actions/unity-build
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ vars.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          target_platform: ${{ matrix.targetPlatform }}
          unity_custom_image: ${{ env.UNITY_CUSTOM_IMAGE_MAC }}
      - name: checkout-self
        uses: actions/checkout@v4
        with:
          repository: shirokurohitsuji/UnityUtilities
          fetch-depth: 0

  post-build-mac:
    name: notarize-for-${{ matrix.targetPlatform }}
    runs-on: macos-latest
    needs:
      - build-mac
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX
    steps:
      - name: notarize
        uses: ./.github/actions/notarize-mac-app
        env:
          target_platform: ${{ matrix.targetPlatform }}
          build_path: ${{ env.PROJECT_PATH }}/build/${{ matrix.targetPlatform }}/${{ env.PROJECT_NAME }}
      - name: checkout-self
        uses: actions/checkout@v4
        with:
          repository: shirokurohitsuji/UnityUtilities
          fetch-depth: 0

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs:
      - build-windows
      - post-build-mac
    steps:
      - name: steam
        uses: ./.github/actions/deploy-to-steam
        env:
          build_version: ${{ needs.build-windows.outputs.buildVersion }}
      - name: checkout-self
        uses: actions/checkout@v4
        with:
          repository: shirokurohitsuji/UnityUtilities
          fetch-depth: 0
      - name: release-on-github
        uses: ./.github/actions/create-release
        env:
          deploy_platform: both
