name: standalone-build

on:
  workflow_call:
    inputs:
      PROJECT_NAME:
        required: true
        type: string
      UNITY_CUSTOM_IMAGE_WINDOWS:
        required: false
        type: string
      UNITY_CUSTOM_IMAGE_MAC:
        required: false
        type: string

env:
  PROJECT_PATH: .
  PROJECT_NAME: ${{ inputs.PROJECT_NAME }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  UNITY_CUSTOM_IMAGE_WINDOWS: ${{ inputs.UNITY_CUSTOM_IMAGE_WINDOWS }}
  UNITY_CUSTOM_IMAGE_MAC: ${{ inputs.UNITY_CUSTOM_IMAGE_MAC }}

jobs:
  build-windows:
    name: build-for-${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
    outputs:
      buildVersion: ${{ steps.build.outputs.buildVersion }}
    steps:
      - name: checkout-self
        uses: actions/checkout@v4
        with:
          repository: shirokurohitsuji/UnityUtilities
          fetch-depth: 0
      - name: prune-previous-images
        run: docker image prune --all --force
        shell: bash
      - name: cache
        uses: ./.github/actions/cache-files
        env:
          target_platform: ${{ matrix.targetPlatform }}
      - name: build
        uses: ./.github/actions/unity-build
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ vars.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          target_platform: ${{ matrix.targetPlatform }}
          unity_custom_image: ${{ env.UNITY_CUSTOM_IMAGE_WINDOWS }}

  prerelease:
    name: prerelease
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master' && github.ref != 'refs/heads/demo'
    needs:
      - build-windows
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64
    steps:
      - name: checkout-self
        uses: actions/checkout@v4
        with:
          repository: shirokurohitsuji/UnityUtilities
          fetch-depth: 0
      - name: release-on-github
        uses: ./.github/actions/create-release
        env:
          deploy_platform: ${{ matrix.targetPlatform }}
